// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: infra/grpc/proto/pokeapi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListPokemonRequest) Reset() {
	*x = ListPokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPokemonRequest) ProtoMessage() {}

func (x *ListPokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPokemonRequest.ProtoReflect.Descriptor instead.
func (*ListPokemonRequest) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{0}
}

func (x *ListPokemonRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPokemonRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPokemonData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ListPokemonData) Reset() {
	*x = ListPokemonData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPokemonData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPokemonData) ProtoMessage() {}

func (x *ListPokemonData) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPokemonData.ProtoReflect.Descriptor instead.
func (*ListPokemonData) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{1}
}

func (x *ListPokemonData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPokemonData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListPokemonsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results  []*ListPokemonData `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Count    int64              `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Next     string             `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	Previous string             `protobuf:"bytes,4,opt,name=previous,proto3" json:"previous,omitempty"`
}

func (x *ListPokemonsResponse) Reset() {
	*x = ListPokemonsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPokemonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPokemonsResponse) ProtoMessage() {}

func (x *ListPokemonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPokemonsResponse.ProtoReflect.Descriptor instead.
func (*ListPokemonsResponse) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{2}
}

func (x *ListPokemonsResponse) GetResults() []*ListPokemonData {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListPokemonsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListPokemonsResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *ListPokemonsResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

type GetPokemonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPokemonRequest) Reset() {
	*x = GetPokemonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonRequest) ProtoMessage() {}

func (x *GetPokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonRequest.ProtoReflect.Descriptor instead.
func (*GetPokemonRequest) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{3}
}

func (x *GetPokemonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Ability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Ability) Reset() {
	*x = Ability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ability) ProtoMessage() {}

func (x *Ability) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ability.ProtoReflect.Descriptor instead.
func (*Ability) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{4}
}

func (x *Ability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ability) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AbilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ability  *Ability `protobuf:"bytes,1,opt,name=ability,proto3" json:"ability,omitempty"`
	IsHidden bool     `protobuf:"varint,2,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	Slot     int64    `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *AbilityResponse) Reset() {
	*x = AbilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityResponse) ProtoMessage() {}

func (x *AbilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityResponse.ProtoReflect.Descriptor instead.
func (*AbilityResponse) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{5}
}

func (x *AbilityResponse) GetAbility() *Ability {
	if x != nil {
		return x.Ability
	}
	return nil
}

func (x *AbilityResponse) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *AbilityResponse) GetSlot() int64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type Form struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Form) Reset() {
	*x = Form{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Form) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Form) ProtoMessage() {}

func (x *Form) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Form.ProtoReflect.Descriptor instead.
func (*Form) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{6}
}

func (x *Form) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Form) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Version) Reset() {
	*x = Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{7}
}

func (x *Version) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Version) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GameIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameIndex int64    `protobuf:"varint,1,opt,name=game_index,json=gameIndex,proto3" json:"game_index,omitempty"`
	Version   *Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GameIndex) Reset() {
	*x = GameIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameIndex) ProtoMessage() {}

func (x *GameIndex) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameIndex.ProtoReflect.Descriptor instead.
func (*GameIndex) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{8}
}

func (x *GameIndex) GetGameIndex() int64 {
	if x != nil {
		return x.GameIndex
	}
	return 0
}

func (x *GameIndex) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{9}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type VersionDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rarity  int64    `protobuf:"varint,1,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Version *Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *VersionDetail) Reset() {
	*x = VersionDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionDetail) ProtoMessage() {}

func (x *VersionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionDetail.ProtoReflect.Descriptor instead.
func (*VersionDetail) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{10}
}

func (x *VersionDetail) GetRarity() int64 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *VersionDetail) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type HeldItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item          *Item            `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	VersionDetail []*VersionDetail `protobuf:"bytes,2,rep,name=version_detail,json=versionDetail,proto3" json:"version_detail,omitempty"`
}

func (x *HeldItem) Reset() {
	*x = HeldItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeldItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeldItem) ProtoMessage() {}

func (x *HeldItem) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeldItem.ProtoReflect.Descriptor instead.
func (*HeldItem) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{11}
}

func (x *HeldItem) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *HeldItem) GetVersionDetail() []*VersionDetail {
	if x != nil {
		return x.VersionDetail
	}
	return nil
}

type MoveDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *MoveDetail) Reset() {
	*x = MoveDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDetail) ProtoMessage() {}

func (x *MoveDetail) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDetail.ProtoReflect.Descriptor instead.
func (*MoveDetail) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{12}
}

func (x *MoveDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MoveDetail) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MoveLearnMethod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *MoveLearnMethod) Reset() {
	*x = MoveLearnMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveLearnMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveLearnMethod) ProtoMessage() {}

func (x *MoveLearnMethod) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveLearnMethod.ProtoReflect.Descriptor instead.
func (*MoveLearnMethod) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{13}
}

func (x *MoveLearnMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MoveLearnMethod) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GroupDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GroupDetail) Reset() {
	*x = GroupDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDetail) ProtoMessage() {}

func (x *GroupDetail) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDetail.ProtoReflect.Descriptor instead.
func (*GroupDetail) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{14}
}

func (x *GroupDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupDetail) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type VersionGroupDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LevelLearnedAt int64        `protobuf:"varint,1,opt,name=level_learned_at,json=levelLearnedAt,proto3" json:"level_learned_at,omitempty"`
	VersionGroup   *GroupDetail `protobuf:"bytes,2,opt,name=version_group,json=versionGroup,proto3" json:"version_group,omitempty"`
}

func (x *VersionGroupDetail) Reset() {
	*x = VersionGroupDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionGroupDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionGroupDetail) ProtoMessage() {}

func (x *VersionGroupDetail) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionGroupDetail.ProtoReflect.Descriptor instead.
func (*VersionGroupDetail) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{15}
}

func (x *VersionGroupDetail) GetLevelLearnedAt() int64 {
	if x != nil {
		return x.LevelLearnedAt
	}
	return 0
}

func (x *VersionGroupDetail) GetVersionGroup() *GroupDetail {
	if x != nil {
		return x.VersionGroup
	}
	return nil
}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Move                *MoveDetail           `protobuf:"bytes,3,opt,name=move,proto3" json:"move,omitempty"`
	VersionGroupDetails []*VersionGroupDetail `protobuf:"bytes,4,rep,name=version_group_details,json=versionGroupDetails,proto3" json:"version_group_details,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{16}
}

func (x *Move) GetMove() *MoveDetail {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *Move) GetVersionGroupDetails() []*VersionGroupDetail {
	if x != nil {
		return x.VersionGroupDetails
	}
	return nil
}

type GetPokemonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BaseExperience int64              `protobuf:"varint,3,opt,name=base_experience,json=baseExperience,proto3" json:"base_experience,omitempty"`
	Height         int64              `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Abilities      []*AbilityResponse `protobuf:"bytes,5,rep,name=abilities,proto3" json:"abilities,omitempty"`
	Forms          []*Form            `protobuf:"bytes,6,rep,name=forms,proto3" json:"forms,omitempty"`
	GameIndices    []*GameIndex       `protobuf:"bytes,7,rep,name=game_indices,json=gameIndices,proto3" json:"game_indices,omitempty"`
	HeldItems      []*HeldItem        `protobuf:"bytes,8,rep,name=held_items,json=heldItems,proto3" json:"held_items,omitempty"`
	Moves          []*Move            `protobuf:"bytes,9,rep,name=moves,proto3" json:"moves,omitempty"`
}

func (x *GetPokemonResponse) Reset() {
	*x = GetPokemonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonResponse) ProtoMessage() {}

func (x *GetPokemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_grpc_proto_pokeapi_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonResponse.ProtoReflect.Descriptor instead.
func (*GetPokemonResponse) Descriptor() ([]byte, []int) {
	return file_infra_grpc_proto_pokeapi_proto_rawDescGZIP(), []int{17}
}

func (x *GetPokemonResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPokemonResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPokemonResponse) GetBaseExperience() int64 {
	if x != nil {
		return x.BaseExperience
	}
	return 0
}

func (x *GetPokemonResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetPokemonResponse) GetAbilities() []*AbilityResponse {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *GetPokemonResponse) GetForms() []*Form {
	if x != nil {
		return x.Forms
	}
	return nil
}

func (x *GetPokemonResponse) GetGameIndices() []*GameIndex {
	if x != nil {
		return x.GameIndices
	}
	return nil
}

func (x *GetPokemonResponse) GetHeldItems() []*HeldItem {
	if x != nil {
		return x.HeldItems
	}
	return nil
}

func (x *GetPokemonResponse) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

var File_infra_grpc_proto_pokeapi_proto protoreflect.FileDescriptor

var file_infra_grpc_proto_pokeapi_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x22, 0x42, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x37,
	0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x91, 0x01, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x07, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x6f, 0x0a, 0x0f, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x07, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x68, 0x69, 0x64, 0x64,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x48, 0x69, 0x64, 0x64,
	0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x2c, 0x0a, 0x04, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0x2f, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x57, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x2b, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2c,
	0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x54, 0x0a, 0x0d,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72,
	0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x2b, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x6e, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x22,
	0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x12, 0x3e, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x0d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x22, 0x32, 0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x37, 0x0a, 0x0f, 0x4d, 0x6f, 0x76, 0x65, 0x4c, 0x65,
	0x61, 0x72, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22,
	0x33, 0x0a, 0x0b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0x7a, 0x0a, 0x12, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x5f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x65, 0x61, 0x72, 0x6e,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x3a, 0x0a, 0x0d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x6f,
	0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x22, 0x82, 0x01, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6d, 0x6f, 0x76,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d,
	0x6f, 0x76, 0x65, 0x12, 0x50, 0x0a, 0x15, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x13, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xe9, 0x02, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x27, 0x0a, 0x0f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x62, 0x61, 0x73, 0x65, 0x45,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x37, 0x0a, 0x09, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x09, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x66, 0x6f,
	0x72, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x6d, 0x73,
	0x12, 0x36, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x0b, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x0a, 0x68, 0x65, 0x6c, 0x64,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x09, 0x68, 0x65, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x6d,
	0x6f, 0x76, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65,
	0x73, 0x32, 0xa4, 0x01, 0x0a, 0x07, 0x50, 0x6f, 0x6b, 0x65, 0x41, 0x50, 0x49, 0x12, 0x4e, 0x0a,
	0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x6f,
	0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x70, 0x6f,
	0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x67, 0x69, 0x6f, 0x76, 0x65, 0x6e, 0x69, 0x63, 0x69, 0x6f,
	0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infra_grpc_proto_pokeapi_proto_rawDescOnce sync.Once
	file_infra_grpc_proto_pokeapi_proto_rawDescData = file_infra_grpc_proto_pokeapi_proto_rawDesc
)

func file_infra_grpc_proto_pokeapi_proto_rawDescGZIP() []byte {
	file_infra_grpc_proto_pokeapi_proto_rawDescOnce.Do(func() {
		file_infra_grpc_proto_pokeapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_infra_grpc_proto_pokeapi_proto_rawDescData)
	})
	return file_infra_grpc_proto_pokeapi_proto_rawDescData
}

var file_infra_grpc_proto_pokeapi_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_infra_grpc_proto_pokeapi_proto_goTypes = []interface{}{
	(*ListPokemonRequest)(nil),   // 0: poke_api.ListPokemonRequest
	(*ListPokemonData)(nil),      // 1: poke_api.ListPokemonData
	(*ListPokemonsResponse)(nil), // 2: poke_api.ListPokemonsResponse
	(*GetPokemonRequest)(nil),    // 3: poke_api.GetPokemonRequest
	(*Ability)(nil),              // 4: poke_api.Ability
	(*AbilityResponse)(nil),      // 5: poke_api.AbilityResponse
	(*Form)(nil),                 // 6: poke_api.Form
	(*Version)(nil),              // 7: poke_api.Version
	(*GameIndex)(nil),            // 8: poke_api.GameIndex
	(*Item)(nil),                 // 9: poke_api.Item
	(*VersionDetail)(nil),        // 10: poke_api.VersionDetail
	(*HeldItem)(nil),             // 11: poke_api.HeldItem
	(*MoveDetail)(nil),           // 12: poke_api.MoveDetail
	(*MoveLearnMethod)(nil),      // 13: poke_api.MoveLearnMethod
	(*GroupDetail)(nil),          // 14: poke_api.GroupDetail
	(*VersionGroupDetail)(nil),   // 15: poke_api.VersionGroupDetail
	(*Move)(nil),                 // 16: poke_api.Move
	(*GetPokemonResponse)(nil),   // 17: poke_api.GetPokemonResponse
}
var file_infra_grpc_proto_pokeapi_proto_depIdxs = []int32{
	1,  // 0: poke_api.ListPokemonsResponse.results:type_name -> poke_api.ListPokemonData
	4,  // 1: poke_api.AbilityResponse.ability:type_name -> poke_api.Ability
	7,  // 2: poke_api.GameIndex.version:type_name -> poke_api.Version
	7,  // 3: poke_api.VersionDetail.version:type_name -> poke_api.Version
	9,  // 4: poke_api.HeldItem.item:type_name -> poke_api.Item
	10, // 5: poke_api.HeldItem.version_detail:type_name -> poke_api.VersionDetail
	14, // 6: poke_api.VersionGroupDetail.version_group:type_name -> poke_api.GroupDetail
	12, // 7: poke_api.Move.move:type_name -> poke_api.MoveDetail
	15, // 8: poke_api.Move.version_group_details:type_name -> poke_api.VersionGroupDetail
	5,  // 9: poke_api.GetPokemonResponse.abilities:type_name -> poke_api.AbilityResponse
	6,  // 10: poke_api.GetPokemonResponse.forms:type_name -> poke_api.Form
	8,  // 11: poke_api.GetPokemonResponse.game_indices:type_name -> poke_api.GameIndex
	11, // 12: poke_api.GetPokemonResponse.held_items:type_name -> poke_api.HeldItem
	16, // 13: poke_api.GetPokemonResponse.moves:type_name -> poke_api.Move
	0,  // 14: poke_api.PokeAPI.ListPokemons:input_type -> poke_api.ListPokemonRequest
	3,  // 15: poke_api.PokeAPI.GetPokemon:input_type -> poke_api.GetPokemonRequest
	2,  // 16: poke_api.PokeAPI.ListPokemons:output_type -> poke_api.ListPokemonsResponse
	17, // 17: poke_api.PokeAPI.GetPokemon:output_type -> poke_api.GetPokemonResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_infra_grpc_proto_pokeapi_proto_init() }
func file_infra_grpc_proto_pokeapi_proto_init() {
	if File_infra_grpc_proto_pokeapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_infra_grpc_proto_pokeapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPokemonData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPokemonsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Form); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeldItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveLearnMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionGroupDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_grpc_proto_pokeapi_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infra_grpc_proto_pokeapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infra_grpc_proto_pokeapi_proto_goTypes,
		DependencyIndexes: file_infra_grpc_proto_pokeapi_proto_depIdxs,
		MessageInfos:      file_infra_grpc_proto_pokeapi_proto_msgTypes,
	}.Build()
	File_infra_grpc_proto_pokeapi_proto = out.File
	file_infra_grpc_proto_pokeapi_proto_rawDesc = nil
	file_infra_grpc_proto_pokeapi_proto_goTypes = nil
	file_infra_grpc_proto_pokeapi_proto_depIdxs = nil
}
